### ISSUE TITLE
why not using meaningful names ?

### ISSUE THREAD

**Issue by tawfiknasser** [facn5/ExpressCars#68]
login.login ?
https://github.com/facn5/ExpressCars/blob/5b86934d5a0e1754988b2094f8d78e35a19c5618/src/server/controllers/router.js#L30

search.search ??
https://github.com/facn5/ExpressCars/blob/5b86934d5a0e1754988b2094f8d78e35a19c5618/src/server/controllers/router.js#L34

utils.js ? give it a good name so who ever look at your code can easily navigate

**Comment by ghost** [comment]
I think that's the most readable names, not really an issue, search is the name for the search file, reviewers would find it the easiet to read it that way, personal preference, not really an issue, review.

**Comment by tawfiknasser** [comment]
:-1:
