### ISSUE TITLE
fix your HTML

### ISSUE THREAD

**Issue by tawfiknasser** [facn5/ExpressCars#69]
https://github.com/facn5/ExpressCars/blob/5b86934d5a0e1754988b2094f8d78e35a19c5618/src/views/layouts/main.hbs#L6-L7
duplecated content in the main 

https://github.com/facn5/ExpressCars/blob/5b86934d5a0e1754988b2094f8d78e35a19c5618/src/views/layouts/home.hbs#L38
 line 38  `</a>`  where did you opened the` <a> `? at home.hbs

you may use HTML validators to check for more fixings

**Comment by ghost** [comment]
There was no bug with the <a> tag, if you looked two lines above there was the <a> , fixed the two seperate "content" tags, please review.

**Comment by tawfiknasser** [comment]
where is the related commit ?

**Comment by ghost** [comment]
I forgot to relate it, https://github.com/facn5/ExpressCars/commit/ac292d42aa67635559a5a2d720a537ef797e8c26
this is the commit tho, review again.
