### ISSUE TITLE
Notes on your github workflow

### ISSUE THREAD

**Issue by tawfiknasser** [facn5/ExpressCars#72]
@mrfong 
1) why did you consider this as bug ?
 https://github.com/facn5/ExpressCars/commit/3d23cd33354d749899092852cf5deb76c9fbc1e4

you replaced `getCars,`
with `getCars:getCars,`
_______________
2)
from commit de61f95 to commit f44e079
4 commit that can be done in 1 commit

___________________
3)  @karam1ashqar 

3733d1c
and 
044320a
Created package.json  and added package.json can be in one commit why two commits ?

no need to  commit when creating folders
26375db
e12c0d6
f66f0f0
6910491
4e8447d
bb48b8f
09a6935
11d9946
9f19946
and more ...
don't add/commit empty folders or files
and no need to sepertaly add commit for each one when you are creating them together 

_________________________
@faris114  
4)
commits with no related issues
f293946e859075b92958cec2381b73de78fcaf38
c1b303cd0e0985d1118d1ba6331c5ac712171a4b
70a91b6399b6d41418adc087c0001425b10f0f13
621346f7ebecbef197048817056b00fdb137c11d
48473ce24d70748d7aaad063a97a718365444cd7
6436c5b242c1abf257c0016b649ef925336488e2
a0e8098021c635fdfdeb75e8ccb4d455bb800f69
and more ...
@mrfong  @karam1ashqar 
7bf758d9a2ddc3fa71bc57987d1b6fd6f45bdee8
0ad6ea0c311e3756c249773fe06c054e9c34a8f2
93a93b23836ca223d2dcee243a9aa1b41e0cdc98
d28566baba20862dddaca0018a27d37b9cf66dc5

**Comment by ghost** [comment]
It wasn't really a bug, commits are not a code to be reviewed, we simply decided on this commit style so they can be seperate and readable, I don't see any issue with that, that's the team's decisions with our workflow.

**Comment by tawfiknasser** [comment]
:-1:
